[config]
[templates.foot]
input_path = "~/.config/matugen/templates/foot.ini"
output_path = "~/.config/foot/theme.ini"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
