# Keyboard
repeat_rate=50
repeat_delay=250
xkb_rules_layout=se

# Mouse
mouse_accel_profile = 0
mouse_accel_speed = -1

# Trackpad
trackpad_accel_profile = 2
trackpad_accel_speed = 0.7

# System
#syncobj_enable = 1
drag_tile_to_tile = 1
drag_corner = 4
no_border_when_single = 0
no_radius_when_single = 0
xwayland_persistence = 0

# Startup
exec-once=dms run
#exec-once=awww-daemon

# Rule
windowrule = noblur:1 unfocused_opacity:1, height:800, width:400, offsetx:-120, isoverlay:1, title:^StreamingChatOverlay$

# isfloating:1, allow_csd:0,  isnoanimation:1,

tagrule = id:1, layout_name:dwindle
tagrule = id:2, layout_name:dwindle
tagrule = id:3, layout_name:dwindle
tagrule = id:4, layout_name:dwindle
tagrule = id:5, layout_name:dwindle
tagrule = id:6, layout_name:dwindle
tagrule = id:7, layout_name:dwindle
tagrule = id:8, layout_name:dwindle
tagrule = id:9, layout_name:dwindle

# Theme
borderpx = 0
gappih = 0
gappiv = 0
gappoh = 0
gappov = 0

focused_opacity = 1
unfocused_opacity = 0.95

# Animations
animation_type_open = zoom
animation_type_close = zoom

animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.5

# Layouts
dwindle_smart_split = 0
dwindle_hsplit = 0
dwindle_vsplit = 0
dwindle_smart_resize = !

# Sub config load
source=./stock-binds.conf
source=./rules.conf
source=./binds.conf
source=./env.conf
source=./monitors.conf
