# Mango
bind=SUPER,r,reload_config
bind=SUPER,m,quit
bind=SUPER,q,killclient,
bind=SUPER,Space,togglefloating,
bind=SUPER,f,togglemaximizescreen,0
bind=SUPER+ctrl,f,togglefullscreen,
bind=SUPER+shift,f,togglefakefullscreen,
bind=SUPER,s,toggle_scratchpad
bind=SUPER+alt,Up,incgaps,+2
bind=SUPER+alt,Down,incgaps,-2

bind=Super,1,view,1
bind=Super,2,view,2
bind=Super,3,view,3
bind=Super,4,view,4
bind=Super,5,view,5
bind=Super,6,view,6
bind=Super,7,view,7
bind=Super,8,view,8
bind=Super,9,view,9

bind=ctrl+Super,1,tag,1
bind=ctrl+Super,2,tag,2
bind=ctrl+Super,3,tag,3
bind=ctrl+Super,4,tag,4
bind=ctrl+Super,5,tag,5
bind=ctrl+Super,6,tag,6
bind=ctrl+Super,7,tag,7
bind=ctrl+Super,8,tag,8
bind=ctrl+Super,9,tag,9

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# resize window
bind=SUPER+CTRL,Up,resizewin,+0,-50
bind=SUPER+CTRL,Down,resizewin,+0,+50
bind=SUPER+CTRL,Left,resizewin,-50,+0
bind=SUPER+CTRL,Right,resizewin,+50,+0

# switch layout
bind=CTRL+SUPER,i,setlayout,dwindle
bind=CTRL+SUPER,l,setlayout,scroller
bind=SUPER,n,switch_layout

# Screenshot
bind=SHIFT,Print,   spawn,$HOME/.config/mango/scripts/screenshot.sh fullscreen
bind=NONE,Print,    spawn,$HOME/.config/mango/scripts/screenshot.sh region
bind=CTRL,Print,    spawn,$HOME/.config/mango/scripts/screenshot.sh window
bind=SUPER,Print,   spawn,$HOME/.config/mango/scripts/screenshot.sh annotate

# Mouse Bindings 
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+CTRL,btn_right,killclient
mousebind=SUPER+CTRL,btn_middle,togglefullscreen
mousebind=SUPER,btn_middle,togglemaximizescreen,0

# DMS
bind=SUPER,d,spawn,dms ipc launcher toggle
bind=SUPER,v,spawn,dms ipc clipboard toggle

# Custom app bind
bind=SUPER,Return,spawn,foot
bind=SUPER,e,spawn,pcmanfm
